"""Generate weights/p2book.py: a compact opening book.

Dev-time only script -- not shipped, not run at runtime. Uses the local
Stockfish binary purely as an offline analysis oracle to pick sound moves
for a BFS tree of opening positions, exactly as the competition rules permit
("Stockfish may only be an offline development teacher"). Nothing here is
copied from Stockfish's own play; it is used only to *rank* candidate moves
generated by python-chess's own legal-move list, and only the resulting
(FEN -> UCI move) pairs are ever shipped, not any Stockfish code or weights.

Produces a FEN-keyed dict (ignoring halfmove/fullmove counters, so a
transposition matches). Branch factor narrows with depth (wide near the root,
where opponent variety matters most; a single best line once deep enough that
another combinatorial doubling would cost far more calls than it is worth) --
see BRANCH_BY_PLY -- so the book reaches deeper main lines without the node
count exploding.
"""

from __future__ import annotations

import json

import chess
import chess.engine

STOCKFISH = "/opt/homebrew/bin/stockfish"
BOOK_PLIES = 14
# branch factor per ply index (0-based); once the list is exhausted, the last
# entry repeats. Wide near the root, narrowing to a single best line deeper.
BRANCH_BY_PLY = [2, 2, 2, 2, 2, 2, 1]
DEPTH = 20


def _branch(ply: int) -> int:
    return BRANCH_BY_PLY[ply] if ply < len(BRANCH_BY_PLY) else BRANCH_BY_PLY[-1]


def _key(board: chess.Board) -> str:
    parts = board.fen().split()
    return " ".join(parts[:4])  # board, side, castling, ep -- drop clocks


def build() -> dict[str, str]:
    book: dict[str, str] = {}
    engine = chess.engine.SimpleEngine.popen_uci(STOCKFISH)
    engine.configure({"Threads": 1})
    try:
        frontier = [chess.Board()]
        for ply in range(BOOK_PLIES):
            branch = _branch(ply)
            next_frontier: list[chess.Board] = []
            for board in frontier:
                key = _key(board)
                if key in book:
                    continue
                info = engine.analyse(
                    board, chess.engine.Limit(depth=DEPTH), multipv=branch
                )
                if not isinstance(info, list):
                    info = [info]
                moves = [pv["pv"][0] for pv in info if pv.get("pv")]
                if not moves:
                    continue
                book[key] = moves[0].uci()
                print(f"ply {ply:2d} (branch {branch})  {key[:40]:40s} -> "
                      f"{[m.uci() for m in moves]}")
                for mv in moves:
                    child = board.copy()
                    child.push(mv)
                    next_frontier.append(child)
            frontier = next_frontier
            print(f"-- ply {ply} done, {len(frontier)} positions in next frontier, "
                  f"{len(book)} book entries so far --")
    finally:
        engine.quit()
    return book


if __name__ == "__main__":
    book = build()
    print(f"total entries: {len(book)}")
    with open("/tmp/claude-501/p2book_data.json", "w") as fh:
        json.dump(book, fh, indent=0)
    print("wrote /tmp/claude-501/p2book_data.json")
